# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authorityID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('authorityname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MTV_Authority',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('authorityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Authority')),
            ],
            options={
                'db_table': 'MTV_user',
            },
        ),
    ]
