# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20170306_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ID', models.CharField(max_length=5)),
                ('label_Name', models.CharField(max_length=255)),
                ('table_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Tables')),
            ],
            options={
                'db_table': 'display_Lables',
            },
        ),
    ]
