# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform_summary_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 3, 6, 7, 41, 30, 809000, tzinfo=utc))),
                ('table_ID', models.CharField(default='1', max_length=5)),
                ('label_ID', models.CharField(max_length=5)),
                ('label_Value', models.DecimalField(decimal_places=1, max_digits=15)),
            ],
            options={
                'db_table': 'display_Platform_summary_day',
            },
        ),
    ]
