# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20170306_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_summary_day',
            name='date',
            field=models.DateTimeField(default=datetime.date(2017, 3, 6)),
        ),
    ]
