# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_ID', models.CharField(max_length=5)),
                ('table_Name', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('module_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Modules')),
            ],
        ),
    ]
