# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20170306_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_summary_day',
            name='date',
            field=models.DateTimeField(default=b'2017-03-06'),
        ),
    ]
